FROM daggerok/jboss-eap-7.2:7.2.0-centos

COPY config/standalone.xml /home/jboss/jboss-eap-7.2/standalone/configuration/standalone.xml

COPY key/jboss.keystore /home/jboss/jboss-eap-7.2/standalone/configuration/
COPY key/jboss.truststore /home/jboss/jboss-eap-7.2/standalone/configuration/