/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.newrelic.nrjmx.v2.nrprotocol;


public enum ResponseType implements org.apache.thrift.TEnum {
  STRING(1),
  DOUBLE(2),
  INT(3),
  BOOL(4),
  ERROR(5);

  private final int value;

  private ResponseType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static ResponseType findByValue(int value) { 
    switch (value) {
      case 1:
        return STRING;
      case 2:
        return DOUBLE;
      case 3:
        return INT;
      case 4:
        return BOOL;
      case 5:
        return ERROR;
      default:
        return null;
    }
  }
}
