name: Build Thrift Docker Image
on:
  workflow_dispatch:
    inputs:
      thrift_version:
        description: 'Thrift version'
        required: true

env:
  THRIFT_VERSION: ${{ github.event.inputs.thrift_version }}

jobs:
  build-thrift-docker-image:
    name: Build Thrift Docker Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.OHAI_DOCKER_HUB_ID }}
          password: ${{ secrets.OHAI_DOCKER_HUB_PASSWORD }}
      - name: Build and push docker image
        run: make ci/docker/publish

