---
name: Push/PR pipeline

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  GPG_MAIL: 'infrastructure-eng@newrelic.com' # info@newrelic.com
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  GPG_PRIVATE_KEY_BASE64: ${{ secrets.GPG_PRIVATE_KEY_BASE64 }} # base64 encoded
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:

  test:
    name: Run tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restore gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
      - name: Build with Gradle
        run: make build
      - name: Package with Gradle
        run: make package
      - name: Install debsigs
        run: sudo apt-get install -y debsigs
      - name: Sign packages
        run: ./script/sign.sh

  snyk:
    name: Run security checks via snyk
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk11@master
        env:
          SNYK_TOKEN: ${{env.SNYK_TOKEN}}
        with:
          args: --severity-threshold=high
