name: Release pipeline

on:
  release:
    types:
      - released
    tags:
      - 'v*'

env:
  GPG_PASSPHRASE: ${{ secrets.OHAI_GPG_PASSPHRASE }}
  GPG_PRIVATE_KEY_BASE64: ${{ secrets.OHAI_GPG_PRIVATE_KEY_BASE64 }}
  TAG: ${{ github.event.release.tag_name }}
  DOCKER_HUB_ID: ${{ secrets.OHAI_DOCKER_HUB_ID }}
  DOCKER_HUB_PASSWORD: ${{ secrets.OHAI_DOCKER_HUB_PASSWORD }}
  SCHEMA_BRANCH: ${{ github.event.release.tag_name }}
  AWS_S3_BUCKET_NAME: "nr-downloads-main"
  AWS_S3_LOCK_BUCKET_NAME: "onhost-ci-lock"
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.OHAI_AWS_ACCESS_KEY_ID_PRODUCTION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.OHAI_AWS_SECRET_ACCESS_KEY_PRODUCTION }}
  AWS_ROLE_ARN: ${{ secrets.OHAI_AWS_ROLE_ARN_PRODUCTION }}
  AWS_ROLE_SESSION_NAME: ${{ secrets.OHAI_AWS_ROLE_SESSION_NAME_PRODUCTION }}

jobs:
  publishing-regular-to-s3:
    name: Publish regular packages to S3 production bucket
    runs-on: ubuntu-latest-4-cores

    steps:
      - name: Debug - Show parameters for regular packages
        run: |
          echo "Regular packages publishing:"
          echo "  app_name: nrjmx"
          echo "  schema: nrjmx"
          
      - name: Publish regular packages to S3
        uses: newrelic/infrastructure-publish-action@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_ROLE_ARN: ${{ env.AWS_ROLE_ARN }}
          AWS_ROLE_SESSION_NAME: ${{ env.AWS_ROLE_SESSION_NAME }}
        with:
          disable_lock: false
          tag: ${{env.TAG}}
          app_name: "nrjmx"
          repo_name: "newrelic/nrjmx"
          schema: "nrjmx"
          aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_s3_bucket_name: ${{ env.AWS_S3_BUCKET_NAME }}
          aws_s3_lock_bucket_name: ${{ env.AWS_S3_LOCK_BUCKET_NAME }}
          access_point_host: "production"
          run_id: ${{ github.run_id }}
          aws_region: ${{ env.AWS_REGION }}
          aws_role_session_name: ${{ env.AWS_ROLE_SESSION_NAME }}
          aws_role_arn: ${{ env.AWS_ROLE_ARN }}
          gpg_passphrase: ${{ env.GPG_PASSPHRASE }}
          gpg_private_key_base64: ${{ env.GPG_PRIVATE_KEY_BASE64 }}

  publishing-fips-to-s3:
    name: Publish FIPS packages to S3 production bucket
    runs-on: ubuntu-latest-4-cores
    needs: [ publishing-regular-to-s3 ]  # Wait for regular publishing
    if: ${{ always() && !cancelled() && !failure() && needs.publishing-regular-to-s3.result == 'success' }}

    steps:
      - name: Debug - Show parameters for FIPS packages
        run: |
          echo "FIPS packages publishing:"
          echo "  app_name: nrjmx-fips"
          echo "  schema: nrjmx-fips"
          
      - name: Publish FIPS packages to S3
        uses: newrelic/infrastructure-publish-action@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_ROLE_ARN: ${{ env.AWS_ROLE_ARN }}
          AWS_ROLE_SESSION_NAME: ${{ env.AWS_ROLE_SESSION_NAME }}
        with:
          disable_lock: false
          tag: ${{env.TAG}}
          app_name: "nrjmx-fips"
          repo_name: "newrelic/nrjmx"
          schema: "nrjmx-fips"
          aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_s3_bucket_name: ${{ env.AWS_S3_BUCKET_NAME }}
          aws_s3_lock_bucket_name: ${{ env.AWS_S3_LOCK_BUCKET_NAME }}
          access_point_host: "production"
          run_id: ${{ github.run_id }}
          aws_region: ${{ env.AWS_REGION }}
          aws_role_session_name: ${{ env.AWS_ROLE_SESSION_NAME }}
          aws_role_arn: ${{ env.AWS_ROLE_ARN }}
          gpg_passphrase: ${{ env.GPG_PASSPHRASE }}
          gpg_private_key_base64: ${{ env.GPG_PRIVATE_KEY_BASE64 }}

  test-packages:
    name: Test package installation from production repo
    runs-on: ubuntu-latest
    needs: [ publishing-regular-to-s3, publishing-fips-to-s3 ]  # Wait for BOTH publishing jobs
    if: ${{ always() && !cancelled() && !failure() && needs.publishing-regular-to-s3.result == 'success' && needs.publishing-fips-to-s3.result == 'success' }}

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_ID }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Test regular package installation from production repo
        uses: newrelic/integrations-pkg-test-action/linux@v1
        with:
          tag: ${{env.TAG}}
          integration: 'nrjmx'
          packageLocation: repo
          upgrade: false
          postInstall: "true"

      - name: Test FIPS package installation from production repo
        uses: newrelic/integrations-pkg-test-action/linux@v1
        with:
          tag: ${{env.TAG}}
          integration: 'nrjmx-fips'
          packageLocation: repo
          upgrade: false
          postInstall: "true"

  finalize-release:
    name: Finalize and notify successful release
    needs: [ publishing-regular-to-s3, publishing-fips-to-s3, test-packages ]
    if: ${{ always() && !cancelled() && !failure() && needs.publishing-regular-to-s3.result == 'success' && needs.publishing-fips-to-s3.result == 'success' && needs.test-packages.result == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Notify successful release
        uses: archive/github-actions-slack@master
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.COREINT_SLACK_TOKEN }}
          slack-channel: ${{ secrets.COREINT_SLACK_CHANNEL }}
          slack-text: "🎉 `${{ github.event.repository.full_name }}`: release promoted successfully! ${{ github.server_url }}/${{ github.event.repository.full_name }}/releases/tag/${{ env.TAG }}"

  notify-failure:
    if: ${{ always() && failure() }}
    needs: [publishing-regular-to-s3, publishing-fips-to-s3, test-packages]
    runs-on: ubuntu-latest
    steps:
      - name: Notify failure via Slack
        uses: archive/github-actions-slack@master
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.COREINT_SLACK_TOKEN }}
          slack-channel: ${{ secrets.COREINT_SLACK_CHANNEL }}
          slack-text: "❌ `${{ github.event.repository.full_name }}`: [release pipeline failed](${{ github.server_url }}/${{ github.event.repository.full_name }}/actions/runs/${{ github.run_id }})."
