---
name: Security Testing

on:
  push:
    branches:
      - master
      - main
      - renovate/**
  pull_request:

jobs:
  scan-java:
    name: Scan Java Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: Run Trivy vulnerability scanner for Java
        uses: aquasecurity/trivy-action@0.34.2
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-java.sarif'
          severity: 'HIGH,CRITICAL'
          skip-dirs: 'gojmx/'
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db

  scan-go:
    name: Scan Go Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner for Go
        uses: aquasecurity/trivy-action@0.34.2
        with:
          scan-type: 'fs'
          scan-ref: 'gojmx/'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-go.sarif'
          severity: 'HIGH,CRITICAL'
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db

  grype:
    name: Grype security scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Grype vulnerability scanner
        uses: anchore/scan-action@v7
        id: grype-inline
        with:
          path: "gojmx/"
          fail-build: true
          severity-cutoff: high
          only-fixed: true
          cache-db: true
          output-format: table