---
name: Testing

env:
  DOCKER_HUB_ID: ${{ secrets.OHAI_DOCKER_HUB_ID }}
  DOCKER_HUB_PASSWORD: ${{ secrets.OHAI_DOCKER_HUB_PASSWORD }}

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - README.md
jobs:
  unit-test-linux:
    name: Linux unit tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_ID }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Running unit tests
        run: make ci/test

  test-go-linux-jdk8:
    name: Linux unit tests for Go on JDK 8
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'gojmx/go.mod'
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_ID }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Running unit tests
        run: make ci/go-test

  test-go-linux-jdk11:
    name: Linux unit tests for Go on JDK 11
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'gojmx/go.mod'
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_ID }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Running unit tests
        run: make ci/go-test-jdk11

  check-gen-code:
    name: Checking generated code
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_ID }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}
      - name: Checking generated code
        run: make ci/check-gen-code

  test-build:
    name: Test jar compilation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_ID }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}
      - name: Build noarch
        run: make ci/build

