name: 🚧 Test NRJMX Package Installation

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version to test'
        required: true
        type: string
        default: '2.9.0'
      repo_endpoint:
        description: 'Repository endpoint to fetch packages from'
        required: false
        type: string
        default: "http://nr-downloads-ohai-staging.s3-website-us-east-1.amazonaws.com"
      platforms:
        description: 'Platforms to test (comma-separated)'
        required: false
        type: string
        default: "al2,al2023,debian-bullseye,debian-bookworm,redhat8,redhat9,redhat10,suse15.3,suse15.4,suse15.5,suse15.6,ubuntu1604,ubuntu1804,ubuntu2004,ubuntu2204,ubuntu2404"

env:
  PACKAGE_VERSION: ${{ inputs.version || 'latest' }}
  REPO_ENDPOINT: ${{ inputs.repo_endpoint || 'http://nr-downloads-ohai-staging.s3-website-us-east-1.amazonaws.com' }}
  TEST_PLATFORMS: ${{ inputs.platforms || 'al2,al2023,debian-bullseye,debian-bookworm,redhat8,redhat9,suse15.3,suse15.4,suse15.5,suse15.6,ubuntu1604,ubuntu1804,ubuntu2004,ubuntu2204,ubuntu2404' }}

jobs:
  test-nrjmx-packages:
    name: Test NRJMX Package Installation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package_type: [standard, fips]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test NRJMX package installation
        uses: newrelic/pkg-installation-testing-action@v1
        with:
          gpg_key: 'http://nr-downloads-ohai-staging.s3-website-us-east-1.amazonaws.com/infrastructure_agent/gpg/newrelic-infra.gpg'
          repo_base_url: ${{ env.REPO_ENDPOINT }}
          package_name: 'nrjmx'
          exec_name: 'nrjmx'
          package_version: '2.9.0'
          platforms: ${{ env.TEST_PLATFORMS }}

  test-results:
    name: Package Installation Test Results
    runs-on: ubuntu-latest
    needs: test-nrjmx-packages
    if: always()
    
    steps:
      - name: Check test results
        run: |
          if [[ "${{ needs.test-nrjmx-packages.result }}" == "success" ]]; then
            echo "✅ All NRJMX package installation tests passed!"
          else
            echo "❌ NRJMX package installation tests failed!"
            exit 1
          fi